// Note: install @faker-js/faker for richer random data (optional)
const uid = () => `${Date.now()}-${Math.floor(Math.random() * 9999)}`;

export type Lead = {
  name: string;
  email: string;
  company?: string;
  phone?: string;
  linkedin_url?: string;
  score?: number;
  status?: "new" | "contacted" | "qualified" | "disqualified";
  source?: string;
  notes?: string;
};

export const createLead = (overrides: Partial<Lead> = {}): Lead => {
  const id = uid();
  return {
    name: `Playwright Lead ${id}`,
    email: `pw.lead.${id}@test.lifetrek.io`,
    company: `Test Company ${id}`,
    phone: "+55 11 99999-0000",
    linkedin_url: `https://linkedin.com/in/pw-lead-${id}`,
    score: 50,
    status: "new",
    source: "playwright-test",
    notes: "Auto-generated by Playwright — safe to delete",
    ...overrides,
  };
};

export const createQualifiedLead = (overrides: Partial<Lead> = {}): Lead =>
  createLead({ status: "qualified", score: 80, ...overrides });

export const createDisqualifiedLead = (overrides: Partial<Lead> = {}): Lead =>
  createLead({ status: "disqualified", score: 10, ...overrides });
